sudo: true
dist: trusty
cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/.cache/travis
        - $HOME/.mx/cache
language: java
python:
    - "2.7"
addons:
    apt:
        sources:
            - deadsnakes
        packages:
            - libgmp3-dev
            - gcc-4.6
            - g++-4.6
            - gfortran-4.6
            - gobjc++-4.6
            - gcc-4.6-plugin-dev
            - libc++1
            - libc++abi1
            - libc++-dev
            - libc++abi-dev
env:
    global:
        # LLVM 3.8
        - LLVM_VERSION=3.8.0
        - LLVM_ARCHIVE_PATH=$HOME/.cache/travis/clang+llvm-$LLVM_VERSION.tar.xz
        # Eclipse JDK
        - ECLIPSE_JDK_ARCHIVE_PATH=$HOME/.cache/travis/eclipse-jdk8.tar.gz
        # ECJ
        - ECJ_VERSION=4.5.2
        - ECJ_ARCHIVE_PATH=$HOME/.cache/travis/ecj-$ECJ_VERSION.jar
        # JVMCI
        - JVMCI_VERSION=0.23
        - JVMCI_ARCHIVE_PATH=$HOME/.cache/travis/jvmci-$JVMCI_VERSION.tar.gz
before_install:
    - mkdir -p $HOME/.cache/travis
    # MDL
    - gem install mdl
    # LLVM 3.8
    - wget -N http://llvm.org/releases/$LLVM_VERSION/clang+llvm-$LLVM_VERSION-x86_64-linux-gnu-ubuntu-14.04.tar.xz -O $LLVM_ARCHIVE_PATH
    - mkdir $HOME/clang+llvm
    - tar xf $LLVM_ARCHIVE_PATH -C $HOME/clang+llvm --strip-components 1
    - export PATH=$HOME/clang+llvm/bin:$PATH
    # Eclipse JDK
    - wget -N https://lafo.ssw.uni-linz.ac.at/pub/sulong-deps/eclipse-jdk8-linux-x86_64.tar.gz -O $ECLIPSE_JDK_ARCHIVE_PATH
    - tar -xvzf $ECLIPSE_JDK_ARCHIVE_PATH -C $HOME
    - export ECLIPSE_EXE=$HOME/eclipse/eclipse
    # ECJ
    - wget -N https://lafo.ssw.uni-linz.ac.at/pub/sulong-deps/ecj-$ECJ_VERSION.jar -O $ECJ_ARCHIVE_PATH
    - export JDT=$ECJ_ARCHIVE_PATH
    # JVMCI
    - wget -N https://github.com/dougxc/openjdk8-jvmci-builder/releases/download/jvmci-$JVMCI_VERSION/jdk1.8.0_111-jvmci-$JVMCI_VERSION-linux-amd64.tar.gz -O $JVMCI_ARCHIVE_PATH
    - tar -xzf $JVMCI_ARCHIVE_PATH -C $HOME
    - export JAVA_HOME=$HOME/jdk1.8.0_111-jvmci-$JVMCI_VERSION
install:
    # Some python libraries
    - pip install astroid==1.1.0 --user
    - pip install pylint==1.1.0 --user
    # MX
    - git clone https://github.com/graalvm/mx.git
    - export PATH=`pwd`/mx:$PATH
    - export MX_BINARY_SUITES="jvmci"
    - export DEFAULT_VM=server
script:
    - $BUILD_COMMAND
    - $TEST_COMMAND
matrix:
    include:
        # Basic checks
        - env:
            - BUILD_COMMAND=''
            - TEST_COMMAND='mx su-checks httpcheck checkstyle mdl eclipseformat pylint ecj canonicalizeprojects checkoverlap --verbose'
          jdk: oraclejdk8
        # LLVM 3.2 testcases
        - env:
            - BUILD_COMMAND='mx build'
            - TEST_COMMAND='mx irbuilder-test32 sulong nwcc llvm'
          jdk: oraclejdk8
        # LLVM 3.8 testcases
        - env:
            - BUILD_COMMAND='mx build'
            - TEST_COMMAND='mx irbuilder-test38 sulong nwcc llvm'
          jdk: oraclejdk8
    allow_failures:
        - env:
            - BUILD_COMMAND='mx build'
            - TEST_COMMAND='mx irbuilder-test32 gcc'
          jdk: oraclejdk8
