sudo: false
cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/.mx/cache
language: java
python:
    - "2.7"
addons:
    apt:
        packages:
            - libgmp3-dev
            - gcc-4.6-plugin-dev
install:
    - pip install astroid==1.1.0 --user
    - pip install pylint==1.1.0 --user
    - git clone https://github.com/graalvm/mx.git
    - export PATH=`pwd`/mx:$PATH
    - export MX_BINARY_SUITES="jvmci"
    - wget https://lafo.ssw.uni-linz.ac.at/pub/sulong-deps/eclipse-jdk8-linux-x86_64.tar.gz
    - tar -xvzf eclipse-jdk8-linux-x86_64.tar.gz
    - export ECLIPSE_EXE=`pwd`/eclipse/eclipse
    - export DEFAULT_VM=server
    - wget -O mx/ecj.jar 'https://lafo.ssw.uni-linz.ac.at/pub/sulong-deps/ecj-4.5.2.jar'
    - export JDT=`pwd`/mx/ecj.jar
    - wget https://github.com/dougxc/openjdk8-jvmci-builder/releases/download/jvmci-0.23/jdk1.8.0_111-jvmci-0.23-linux-amd64.tar.gz
    - tar -xzf jdk1.8.0_111-jvmci-0.23-linux-amd64.tar.gz
    - export JAVA_HOME=`pwd`/jdk1.8.0_111-jvmci-0.23
script:
    - mx build -f -p --warning-as-error
    - mx checkstyle
    - mx eclipseformat --primary
    - mx pylint
    - mx checkoverlap
    - mx canonicalizeprojects
    - mx clean & mx build
    - mx irbuilder-test32
    - mx irbuilder-test38
